version: '3'

services:
  app:
    build: .
    volumes:
      - .dockerenv:/app/.venv
      - .:/app
    ports:
      - 8000:8000
    tty: true
    stdin_open: true
    depends_on:
      - db-test
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432

  db-test:
    image: postgres:15
    container_name: postgres-db-test
    volumes:
      - postgres_data_test:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres-test
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres-test
    ports:
      - 5433:5432

volumes:
  postgres_data:
  postgres_data_test:

