name: Flake8 Lint

on: [push]

jobs:
  flake8-lint:

    runs-on: ubuntu-latest
    name: Lint

    steps:
      - name: Check out source repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Cache Poetry cache
        uses: actions/cache@v3
        id: poetry_cache
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install Pip
        run: python -m pip install --upgrade pip 

      - name: Install Poetry
        run: pip install poetry | 
          poetry --version

      - name: install dependencies
        if: steps.poetry_cache_id.outputs.cache-hit != 'true'
        run: |
          poetry install --no-root

      - name: Lint with flake8
        run: |
          poetry run flake8 src tests
